// Playlist images with labels - update this list with actual image filenames from /public/playlist
export const playlistImages = [
  { image: "Top10.png", label: "Top 10 of the Week" },
  { image: "dhurandhar.png", label: "Dhurandhar" },
  { image: "god.png", label: "Spiritual" },
  { image: "Disney.png", label: "Disney & Pixar" },
  { image: "oldmelodies.png", label: "Old Melodies" },
  { image: "cartoon.png", label: "Cartoon" },
  { image: "bengali.png", label: "বাংলা Bangla" },
  { image: "bharat.png", label: "Bharat" },
  { image: 'chillvibes.png', label: 'Chill Vibes' },
  { image: "edm.png", label: "EDM" },
  { image: "Globalmusic.png", label: "Global Hits" },
  { image: "gym.png", label: "Gym" },
  { image: "holi.png", label: "Holi" },
  { image: 'party.png', label: 'Party' },
  { image: "romantic.png", label: "Romantic" },
  { image: "thar.png", label: "Thar" },
  { image: "valentine.png", label: "Valentine" },
  { image: "Sallu.png", label: "Sallu-Bhai" },
];
