/**
 * Theme options from master taxonomy (genres, languages, moods, song types).
 * Used for Moods > Themes filter.
 */
export const THEME_OPTIONS = [
  "Bollywood",
  "Pop",
  "Dance Pop",
  "Rock",
  "Hip-Hop / Rap",
  "EDM",
  "Jazz",
  "Acoustic",
  "Punjabi Pop",
  "Tamil / Telugu Film Music",
  "Devotional (Bhajan / Aarti / Kirtan)",
  "Sufi",
  "Hindi",
  "English",
  "Marathi",
  "Punjabi",
  "Tamil",
  "Telugu",
  "Spanish",
  "Romantic",
  "Love",
  "Party",
  "Peppy",
  "Energetic",
  "Dance",
  "Happy",
  "Sad",
  "Soulful",
  "Spiritual",
  "Motivational",
  "Chill",
  "Feel Good",
  "Friendship / Dosti",
  "Party Song",
  "Item Song",
  "Dance Number",
  "Club Song",
  "Romantic Song",
  "Devotional",
  "Celebration Song",
];
